import os
import re
import json
import time
import html as _html
from pathlib import Path
from flask import Flask, render_template, jsonify, request
from flask_cors import CORS

# Load .env so the dashboard works locally without manual env var setup
_env = Path(__file__).parent / ".env"
if _env.exists():
    for _line in _env.read_text().splitlines():
        if _line.strip() and not _line.startswith("#") and "=" in _line:
            _k, _v = _line.split("=", 1)
            os.environ.setdefault(_k.strip(), _v.strip())

import anthropic
from piazza_api import Piazza

BASE_DIR = Path(__file__).parent

app = Flask(__name__, template_folder=str(BASE_DIR / "templates"))
CORS(app)

# ── Answer quality checklist (CHEM 11 only) ──────────────────────────────────

_CHECKLIST = [
    (r"[—–]",                                                   "em/en dash"),
    (r";",                                                       "semicolon"),
    (r"(?m)^\s*[-•*]\s",                                        "bullet point"),
    (r"(?m)^\s*\d+\.\s",                                        "numbered list"),
    (r"\*\*|__|\*[^*\s]|_[^_\s]",                              "markdown formatting"),
    (r"(?i)^(hi|hello|hey|dear|greetings)[,!\s]",              "greeting at start"),
    (r"(?i)(hope this helps|let me know|feel free|any questions|good luck|don't hesitate)", "sign-off phrase"),
    (r"(?i)(as an ai|i'm an ai|language model|i'm claude|ai assistant)", "AI self-identification"),
    (r"(?i)(great question|excellent question|good question|that's a great)", "sycophantic opener"),
    (r"(?i)(furthermore|it is important to note|it's important to note|in conclusion|in summary)", "AI filler phrase"),
    (r"(?i)(you should|you need to|make sure you|remember to|always remember|don't forget|i recommend|i suggest|my advice|pro tip)", "advice/tip"),
]

_MIN_WORDS = 30
_MAX_WORDS = 250

def _check_answer(text):
    failures = []
    for pattern, msg in _CHECKLIST:
        if re.search(pattern, text):
            failures.append(msg)
    words = len(text.split())
    if words < _MIN_WORDS:
        failures.append(f"too short ({words} words)")
    if words > _MAX_WORDS:
        failures.append(f"too long ({words} words)")
    return failures


# ── System prompts for manual response generation ─────────────────────────────

_COGS9_GENERATE_SYSTEM = """\
You are a helpful teaching assistant for COGS 9 (Introduction to Data Science) at UCSD. \
A student posted a question on Piazza. Generate a clear, helpful, and accurate response.

{syllabus_section}

Guidelines:
- Be friendly and encouraging
- Be concise but complete — no unnecessary filler
- For logistics/policy questions: answer from the syllabus when possible
- For data science concept questions: give a clear conceptual explanation
- Do NOT prefix with "Here is an answer:" — respond directly as a TA would
- End with: "\\n\\n🤖 This response was generated by Claude AI — please verify against the official course syllabus.\""""

_CHEM11_GENERATE_SYSTEM = """\
You are writing a Piazza answer for CHEM 11 (Introduction to General Chemistry for non-science \
majors) at UCSD. Textbook: Fundamentals of General, Organic, and Biological Chemistry, 8th ed. \
(McMurry et al.). Topics: Matter & Measurements, Atoms & the Periodic Table, Ionic Compounds, \
Molecular Compounds, Chemical Reactions, Stoichiometry, Energy/Rates/Equilibrium, \
Gases/Liquids/Solids, Solutions.

Answer at the scope of a first year college student. Keep your responses as if you were typing \
a quick message to a classmate between classes. The message should pass as a serious sounding \
real person, not an AI. Keep it mostly formal, polite, and straight to the point. Basically just \
answer it as briefly yet properly as possible.

REQUIRED FORMAT -- every rule below is mandatory:
Do not use em dashes (--) or en dashes. Use a comma or period instead.
Do not use semicolons (;). Split into separate sentences instead.
Do not use bullet points, numbered lists, or any list formatting.
Do not use bold, italics, headers, or any markdown.
Do not open with a greeting of any kind (no Hi, Hello, Hey, Dear, etc.).
Do not close with any follow-up, sign-off, or pleasantry (no "Hope this helps", "Let me know", "Feel free", "Any questions", "Good luck", etc.).
Do not identify yourself as an AI or reference Claude, AI, or language models in any way.
Do not open with a compliment on the question (no "Great question", "Good question", etc.).
Do not use filler phrases like "Furthermore", "It is important to note", "In conclusion", or "In summary".
Do not sound condescending or superior. You are a peer, not a teacher.
Do not give advice, tips, or suggestions. Only answer what was directly asked.
Do not use rhetorical questions to lead into your answer. Start with the answer itself.
Write between 30 and 250 words.
End your response with the last relevant word of your answer and nothing after it.\
"""

# ── Piazza lazy connection ────────────────────────────────────────────────────

_piazza_networks = None  # dict: {"COGS 9": network, "CHEM 11": network}


def _get_piazza_networks():
    global _piazza_networks
    if _piazza_networks is not None:
        return _piazza_networks

    email    = os.environ.get("PIAZZA_EMAIL", "")
    password = os.environ.get("PIAZZA_PASSWORD", "")
    if not email or not password:
        raise RuntimeError("PIAZZA_EMAIL / PIAZZA_PASSWORD not configured in environment")

    p = Piazza()
    p.user_login(email=email, password=password)

    networks = {}
    cogs9_id  = os.environ.get("PIAZZA_NETWORK") or os.environ.get("PIAZZA_NETWORK_COGS9")
    chem11_id = os.environ.get("CHEM_PIAZZA_NETWORK") or os.environ.get("PIAZZA_NETWORK_CHEM11")
    if cogs9_id:
        networks["COGS 9"] = p.network(cogs9_id)
    if chem11_id:
        networks["CHEM 11"] = p.network(chem11_id)

    _piazza_networks = networks
    return networks


# ── Helpers ───────────────────────────────────────────────────────────────────

def _read_json_file(path):
    """Read a JSON file, return None if missing or corrupt."""
    try:
        return json.loads(Path(path).read_text())
    except Exception:
        return None


def _is_pid_alive(pid):
    """Check if a process is alive via os.kill(pid, 0)."""
    if pid is None:
        return False
    try:
        os.kill(int(pid), 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True  # exists but owned by another user
    except Exception:
        return False


# ── Routes ────────────────────────────────────────────────────────────────────

@app.route("/")
def index():
    return render_template("dashboard.html")


@app.route("/api/status")
def api_status():
    bot_a_data = _read_json_file(BASE_DIR / "bot_status.json")
    if bot_a_data and isinstance(bot_a_data, dict):
        bot_a_data["alive"] = _is_pid_alive(bot_a_data.get("pid"))
    else:
        bot_a_data = {
            "bot": "A", "course": "COGS 9", "status": "not_started",
            "pid": None, "last_scan": None, "scan_count": 0,
            "posts_answered": 0, "seen_count": 0, "poll_interval": None,
            "last_post": None, "alive": False,
        }

    bot_b_data = _read_json_file(BASE_DIR / "assistant_b_status.json")
    if bot_b_data and isinstance(bot_b_data, dict):
        bot_b_data["alive"] = _is_pid_alive(bot_b_data.get("pid"))
    else:
        bot_b_data = {
            "bot": "B", "course": "CHEM 11", "status": "not_started",
            "pid": None, "last_scan": None, "scan_count": 0,
            "posts_answered": 0, "post_limit": None, "objective_complete": False,
            "seen_count": 0, "poll_interval": None, "last_post": None, "alive": False,
        }

    return jsonify({"botA": bot_a_data, "botB": bot_b_data})


@app.route("/api/activity")
def api_activity():
    entries = _read_json_file(BASE_DIR / "activity_log.json")
    if not isinstance(entries, list):
        entries = []
    return jsonify(list(reversed(entries[-50:])))


@app.route("/api/scan_log")
def api_scan_log():
    """Return last 100 scanned questions (all categories), most recent first."""
    entries = _read_json_file(BASE_DIR / "scan_log.json")
    if not isinstance(entries, list):
        entries = []
    return jsonify(list(reversed(entries[-100:])))


@app.route("/api/generate", methods=["POST"])
def api_generate():
    """
    Generate a response for a question using Claude.
    Body: { "question": "...", "course": "COGS 9" | "CHEM 11" }
    Returns: { "answer": "..." }
    """
    data     = request.get_json() or {}
    question = (data.get("question") or "").strip()
    course   = (data.get("course") or "").strip()

    if not question:
        return jsonify({"error": "question is required"}), 400

    try:
        client = anthropic.Anthropic()

        if course == "CHEM 11":
            system = _CHEM11_GENERATE_SYSTEM
        else:
            syllabus_path = BASE_DIR / os.environ.get("SYLLABUS_PATH", "syllabus.txt")
            try:
                syllabus_text    = syllabus_path.read_text(encoding="utf-8").strip()
                syllabus_section = f"SYLLABUS:\n{syllabus_text}"
            except Exception:
                syllabus_section = ""
            system = _COGS9_GENERATE_SYSTEM.format(syllabus_section=syllabus_section)

        answer = ""
        violations = []
        for attempt in range(3):
            resp = client.messages.create(
                model="claude-haiku-4-5",
                max_tokens=400,
                system=system,
                messages=[{"role": "user", "content": question}],
            )
            answer = "".join(b.text for b in resp.content if b.type == "text").strip()
            if course == "CHEM 11":
                violations = _check_answer(answer)
                if not violations:
                    break
            else:
                break

        payload = {"answer": answer}
        if violations:
            payload["warnings"] = violations
        return jsonify(payload)

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/api/send", methods=["POST"])
def api_send():
    """
    Post a manually reviewed answer to Piazza.
    Body: { "cid": "...", "answer": "...", "course": "COGS 9" | "CHEM 11" }
    Returns: { "ok": true, "type": "s_answer" } or { "error": "..." }
    """
    data   = request.get_json() or {}
    cid    = (data.get("cid") or "").strip()
    answer = (data.get("answer") or "").strip()
    course = (data.get("course") or "").strip()

    if not cid or not answer:
        return jsonify({"error": "cid and answer are required"}), 400

    try:
        networks = _get_piazza_networks()
        network  = networks.get(course)
        if not network:
            return jsonify({"error": f"No Piazza network configured for: {course}"}), 400

        network._rpc.content_student_answer(cid, answer, revision=0)
        return jsonify({"ok": True, "type": "s_answer"})

    except RuntimeError as e:
        return jsonify({"error": str(e)}), 503
    except Exception as e:
        return jsonify({"error": f"Piazza post failed: {e}"}), 500


# ── All-posts cache ───────────────────────────────────────────────────────────

_POSTS_CACHE_PATH = BASE_DIR / "posts_cache.json"
_POSTS_CACHE_TTL  = 300  # seconds


def _strip_html(raw):
    return _html.unescape(re.sub(r"<[^>]+>", " ", raw or "")).strip()


def _is_posts_cache_fresh():
    if not _POSTS_CACHE_PATH.exists():
        return False
    cache_mtime = _POSTS_CACHE_PATH.stat().st_mtime
    if (time.time() - cache_mtime) >= _POSTS_CACHE_TTL:
        return False
    # Invalidate if scan_log changed after the cache was written
    scan_log_path = BASE_DIR / "scan_log.json"
    if scan_log_path.exists() and scan_log_path.stat().st_mtime > cache_mtime:
        return False
    return True


def _build_all_posts(limit=500):
    """Fetch all posts from Piazza, merged with scan_log gate results."""
    networks = _get_piazza_networks()

    scan_log = _read_json_file(BASE_DIR / "scan_log.json") or []
    if not isinstance(scan_log, list):
        scan_log = []
    scan_map = {
        (e.get("course", ""), str(e.get("nr", ""))): e
        for e in scan_log
    }

    posts = []
    for course, network in networks.items():
        for post in network.iter_all_posts(limit=limit):
            if post.get("type") != "question":
                continue
            nr  = post.get("nr", 0)
            cid = post.get("id", "")
            hist = (post.get("history") or [{}])[0]
            question = (
                _strip_html(hist.get("subject", "")) + "\n" +
                _strip_html(hist.get("content", ""))
            ).strip()

            has_answer = any(
                c.get("type") in ("i_answer", "s_answer")
                for c in post.get("children", [])
            )

            s          = scan_map.get((course, str(nr)), {})
            bot_posted = bool(s.get("posted"))
            posts.append({
                "nr":         nr,
                "cid":        cid,
                "course":     course,
                "question":   question[:400],
                "has_answer": has_answer,
                "bot_posted": bot_posted,
                "posted":     bot_posted,
                "category":   "bot" if bot_posted else (s.get("category") or ("answered" if has_answer else "")),
                "gate_answer": s.get("gate_answer") or "",
                "source":     s.get("source") or "",
                "time":       s.get("time") or "",
            })

    posts.sort(key=lambda x: x.get("nr") or 0, reverse=True)
    return posts


@app.route("/api/all_posts")
def api_all_posts():
    """Return all Piazza posts (questions), merged with scan_log. 5-min cache."""
    force = request.args.get("refresh") == "1"

    if not force and _is_posts_cache_fresh():
        cached = _read_json_file(_POSTS_CACHE_PATH)
        if cached and isinstance(cached.get("posts"), list):
            return jsonify({
                "posts":      cached["posts"],
                "fetched_at": cached.get("fetched_at"),
                "from_cache": True,
            })

    try:
        posts   = _build_all_posts()
        payload = {
            "posts":      posts,
            "fetched_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "from_cache": False,
        }
        try:
            _POSTS_CACHE_PATH.write_text(json.dumps(payload))
        except Exception:
            pass
        return jsonify(payload)

    except RuntimeError as e:
        return jsonify({"error": str(e)}), 503
    except Exception as e:
        cached = _read_json_file(_POSTS_CACHE_PATH)
        if cached and isinstance(cached.get("posts"), list):
            return jsonify({**cached, "from_cache": True, "stale": True})
        return jsonify({"error": str(e)}), 500


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=5050, debug=True)
